import 'package:foxfit_test/model/transaction.dart';

enum CurrencyType { crypto, wire }

enum TransactionType { buy, sell }

enum Currency { usd, btc, dot, ton }

final transactions = [
  Transaction(
    transactionType: TransactionType.buy,
    currencyType: CurrencyType.crypto,
    fiatCurrency: Currency.usd,
    cryptoCurrency: Currency.btc,
    amountFrom: 17856.22,
    amountTo: 1.00,
    rate: 17856.22,
    date: DateTime.fromMillisecondsSinceEpoch(1667902363000),
  ),
  Transaction(
    transactionType: TransactionType.sell,
    currencyType: CurrencyType.crypto,
    fiatCurrency: Currency.usd,
    cryptoCurrency: Currency.btc,
    amountFrom: 35712.44,
    amountTo: 2.00,
    rate: 17856.22,
    date: DateTime.fromMillisecondsSinceEpoch(1667904863000),
  ),
  Transaction(
    transactionType: TransactionType.buy,
    currencyType: CurrencyType.crypto,
    fiatCurrency: Currency.usd,
    cryptoCurrency: Currency.btc,
    amountFrom: 19336.79,
    amountTo: 1.00,
    rate: 19336.79,
    date: DateTime.fromMillisecondsSinceEpoch(1667635543000),
  ),
  Transaction(
    transactionType: TransactionType.buy,
    currencyType: CurrencyType.crypto,
    fiatCurrency: Currency.usd,
    cryptoCurrency: Currency.btc,
    amountFrom: 19336.79,
    amountTo: 1.00,
    rate: 19336.79,
    date: DateTime.fromMillisecondsSinceEpoch(1667635543000),
  ),
  Transaction(
    transactionType: TransactionType.buy,
    currencyType: CurrencyType.crypto,
    fiatCurrency: Currency.usd,
    cryptoCurrency: Currency.btc,
    amountFrom: 19336.79,
    amountTo: 1.00,
    rate: 19336.79,
    date: DateTime.fromMillisecondsSinceEpoch(1667635543000),
  ),
  Transaction(
    transactionType: TransactionType.buy,
    currencyType: CurrencyType.crypto,
    fiatCurrency: Currency.usd,
    cryptoCurrency: Currency.btc,
    amountFrom: 19336.79,
    amountTo: 1.00,
    rate: 19336.79,
    date: DateTime.fromMillisecondsSinceEpoch(1667635543000),
  ),
  Transaction(
    transactionType: TransactionType.buy,
    currencyType: CurrencyType.crypto,
    fiatCurrency: Currency.usd,
    cryptoCurrency: Currency.btc,
    amountFrom: 19336.79,
    amountTo: 1.00,
    rate: 19336.79,
    date: DateTime.fromMillisecondsSinceEpoch(1667635543000),
  ),
  Transaction(
    transactionType: TransactionType.buy,
    currencyType: CurrencyType.crypto,
    fiatCurrency: Currency.usd,
    cryptoCurrency: Currency.btc,
    amountFrom: 19336.79,
    amountTo: 1.00,
    rate: 19336.79,
    date: DateTime.fromMillisecondsSinceEpoch(1667635543000),
  ),
  Transaction(
    transactionType: TransactionType.buy,
    currencyType: CurrencyType.crypto,
    fiatCurrency: Currency.usd,
    cryptoCurrency: Currency.btc,
    amountFrom: 19336.79,
    amountTo: 1.00,
    rate: 19336.79,
    date: DateTime.fromMillisecondsSinceEpoch(1667635543000),
  ),
  Transaction(
    transactionType: TransactionType.buy,
    currencyType: CurrencyType.crypto,
    fiatCurrency: Currency.usd,
    cryptoCurrency: Currency.btc,
    amountFrom: 19336.79,
    amountTo: 1.00,
    rate: 19336.79,
    date: DateTime.fromMillisecondsSinceEpoch(1667635543000),
  ),
  Transaction(
    transactionType: TransactionType.buy,
    currencyType: CurrencyType.crypto,
    fiatCurrency: Currency.usd,
    cryptoCurrency: Currency.btc,
    amountFrom: 19336.79,
    amountTo: 1.00,
    rate: 19336.79,
    date: DateTime.fromMillisecondsSinceEpoch(1667635543000),
  ),
  Transaction(
    transactionType: TransactionType.buy,
    currencyType: CurrencyType.crypto,
    fiatCurrency: Currency.usd,
    cryptoCurrency: Currency.btc,
    amountFrom: 19336.79,
    amountTo: 1.00,
    rate: 19336.79,
    date: DateTime.fromMillisecondsSinceEpoch(1667635543000),
  ),
];
